version: '3'


services:
   db:
    image: postgres:14
    container_name: taskDB
    environment:
     - POSTGRES_USER=admin
     - POSTGRES_DB=task
     - POSTGRES_PASSWORD=admin_123
    ports:
     - 5433:5432
    volumes:
     - ./data:/var/lib/postgresql/data  